---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible
  - pip install dopy==0.3.5

script:
  # Basic role syntax check
  - ansible-playbook test.yml --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email: false
